# Generated by Django 5.0.6 on 2024-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employments',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Тип занятости')),
            ],
            options={
                'verbose_name': 'Тип занятости',
                'verbose_name_plural': 'Типы занятости',
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыты работы',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='График работы')),
                ('uid', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
