# Generated by Django 5.0.6 on 2024-07-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancies',
            name='name',
            field=models.CharField(default='vacancy name', max_length=500, verbose_name='Название вакансии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancies',
            name='salary',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Размер заработной платы'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/', verbose_name='Ссылка на вакансию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID вакансии'),
        ),
    ]
